### ISSUE TITLE
Unexpected : 

### ISSUE THREAD

**Issue by AussieEevee** [xivapi/xivapi-php#8]
PHP throws the following error when trying to load the API:

`[18-Jun-2019 17:51:12 Australia/Perth] PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /home/*****/*****.net/****/admin/XIVAPI/XIVAPI.php on line 70`

**Comment by vekien** [comment]
What version of PHP are you running? It requires PHP 7.2+

**Comment by AussieEevee** [comment]
Turns out my host has a switch for changing the PHP version, and I didn't know that... It was running on 5.6.

Sorry about that.
